language: python
sudo: false

python:
    - "3.4"
    - "3.5"
    - "3.5.2"

before_install:
    - cp example.env .env

install:
    - pip install -r requirements.txt

before_script:
    # Make sure the version of the dependent packages are correct on Travis CI.
    - pip freeze

script:
    - python manage.py test
